ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:source-highlighter: :rouge:
endif::[]

= i.MX Docker Applications

This repo is intend to explain how to run applications (_OpenCL_, _OpenCV_, _Machine Learning_, etc.) using https://www.docker.com/resources/what-container[Docker Container] on https://source.codeaurora.org/external/imx/imx-manifest/[i.MX BSP releases] - the hardware used
in this tutorial is an https://www.nxp.com/design/development-boards/i.mx-evaluation-and-development-boards/i.mx-8quadmax-multisensory-enablement-kit-mek:MCIMX8QM-CPU[i.MX8 QM MEK Board].

Before starting with Docker, ensure you have an i.MX image with all dependencies installed:

* <<building_yocto>>.

Create your own image using the following base:

* https://github.com/diegohdorta/docker-imx/tree/master/docker/base[Docker Base for Arm64v8 Ubuntu 16.04].

You can test the following applications using Docker on i.MX:

* https://github.com/diegohdorta/docker-imx/tree/master/docker/clinfo[Clinfo - OpenCL Platforms and Devices Printer].
* https://github.com/diegohdorta/docker-imx/tree/master/docker/clpeak[Clpeak - Benchmarking Tool to Measure Peak Capabilities of OpenCL Devices].

[NOTE]
====
This tutorial is fully based on GNU/Linux Distribution Ubuntu `18.04` as host machine.
====

[[building_yocto]]
== Building Yocto Image

=== Software Requirements

. Install the essential packages for _Yocto Project_ host:
+
[source,console]
----
~# apt update
~# apt install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential \
   chrpath socat libsdl1.2-dev && apt clean
----
+
. Install the essential packages for _Yocto Project_ layers:
+
[source,console]
----
~# apt install libsdl1.2-dev xterm sed cvs subversion coreutils texi2html docbook-utils \
   python-pysqlite2 help2man gcc g++ make desktop-file-utils libgl1-mesa-dev libglu1-mesa-dev \
   mercurial autoconf automake groff curl lzop asciidoc u-boot-tools  && apt clean
----

=== Setting Up Yocto Environment

[IMPORTANT]
====
The following steps can be used in any i.MX BSP releases. The latest BSP available is `4.19.35`.
====

. Follow the steps on https://source.codeaurora.org/external/imx/imx-manifest/about/[imx-manifest] to download manifests for i.MX BSP releases.
+
. Create a folder:
+
[source,console]
----
~$ mkdir yocto
~$ cd yocto
----
+
. Use the latest https://source.codeaurora.org/external/imx/imx-manifest/log/?h=imx-linux-warrior[imx-linux-warrior] branch from `4.19.35` i.MX BSP release:
+
[source,console]
----
~yocto$ repo init -u git://source.codeaurora.org/external/imx/imx-manifest.git -b imx-linux-warrior -m imx-4.19.35-1.1.0.xml
~yocto$ repo sync
----
+
. Retrieve the https://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/tree/README[meta-virtualization] layer to _sources_ folder:
+
[source,console]
----
~yocto$ git clone https://git.yoctoproject.org/git/meta-virtualization sources/meta-virtualization -b warrior
----

=== Yocto Building Process

. Create the build project:
+
[source,console]
----
~yocto$ EULA=1 MACHINE=imx8qmmek DISTRO=fsl-imx-xwayland source ./fsl-setup-release.sh -b bld-dir
----
+
. Update the `bblayers.conf` file adding the _meta-virtualization_ layer:
+
[source,console]
----
~yocto/bld-dir$ echo "BBLAYERS += \" \${BSPDIR}/sources/meta-virtualization \"" >> conf/bblayers.conf
----
+
. Update the `local.conf` adding the next packages and configurations:
+
.. **EXTRA SPACE**:
+
[source,console]
----
IMAGE_ROOTFS_EXTRA_SPACE = " 5000000 "
----
+
[TIP]
====
This can be manually changed later using any partition manager tool.
====
+
.. **DOCKER REQUIREMENTS**
+
[source,console]
----
DISTRO_FEATURES_append = " virtualization "
IMAGE_INSTALL_append += " docker docker-contrib connman connman-client "
CORE_IMAGE_EXTRA_INSTALL += " openssh "
----
+
.. **DEVELOPMENT CAPABILITIES**
+
[source,console]
----
EXTRA_IMAGE_FEATURES = " dev-pkgs debug-tweaks tools-debug ssh-server-openssh "
TOOLCHAIN_HOST_TASK_append = " nativesdk-cmake nativesdk-make "
----
+
.. **NETWORK CAPABILITIES**
+
[source,console]
----
IMAGE_INSTALL_append = " net-tools iputils dhcpcd "
----
+
.. **EXTRA SOFTWARE/TOOLS**:
+
[source,console]
----
IMAGE_INSTALL_append = " python python-pip python3 python3-pip"
IMAGE_INSTALL_append = " wget git zlib vim tar unzip grep tmux swig \
                         cmake make gtest parted e2fsprogs e2fsprogs-resize2fs "
----
+
. Build the image:
+
[source,console]
----
~yocto/bld-dir$ bitbake fsl-image-qt5
----
+
. To flash the image to `SD Card`:
+
.. Uncompress the image:
+
[source,console]
----
~yocto/bld-dir$ cd tmp/deploy/images/
~yocto/bld-dir/tmp/deploy/images/$ bunzip2 <image>.sdcard.bzip2
----
+
.. Flash the image:
+
[source,console]
----
~yocto/bld-dir/tmp/deploy/images/# dd if=<image>.sdcard of=/dev/sd<x> bs=1M status=progress && sync
----
+
[CAUTION]
====
_**<x>**_ refers to the SD Card device. You can check by listing the block devices: `lsblk`.
====

=== LICENSE

The `i.MX Docker Applications` is licensed under the https://github.com/diegohdorta/docker-imx/blob/master/LICENSE[BSD 3-Clause License] © 2019 NXP Semiconductor.
